<?php


// include the email and db config
include( 'config.php' );


// include phpmailer
// include( "lib/phpmailer/class.phpmailer.php" );


// email validation function
function valid_email( $email ) {
	$email_valid=filter_var( $email, FILTER_VALIDATE_EMAIL);
	if ( $email_valid ) {
		return true;
	}
	return false;
}


// database object
class db {
	protected $cn='';
	public $result='';
	public $show_errors=true;

	function db() {
		$this->cn=@mysql_connect( DB_HOST, DB_USER, DB_PASS);
		mysql_select_db( DB_NAME );
	}

	function query( $query ) {
		$select=mysql_query( $query,$this->cn );
		if ( is_resource( $select ) ) {
			while ( $rowselect=mysql_fetch_object( $select ) ) {
				$results[]=$rowselect;
			}
		}
		if ( !empty( $results ) ) {
			return $results;
		} else {
			$this->handle_error();
			return false;
		}
	}

	function query_one( $query ) {
		$select=mysql_query( $query,$this->cn );
		if ( is_resource( $select ) ) {
			while ( $rowselect=mysql_fetch_object( $select ) ) {
				$results[]=$rowselect;
			}
		}
		if ( !empty( $results ) ) {
			return $results[0];
		} else {
			$this->handle_error();
			return false;
		}
	}

	function update( $query ) {
		$update=mysql_query( $query, $this->cn );
		if ( $update ) {
			return true;
		} else {
			$this->handle_error();
			return false;
		}
	}

	function insert( $query ) {
		$update=mysql_query( $query, $this->cn );
		if ( $update ) {
			return mysql_insert_id();
		} else {
			$this->handle_error();
			return false;
		}
	}

	function handle_error() {
		$error=mysql_error();
		if ( !empty( $error ) && $this->show_errors ) {
			print $error;
			die;
		}
	}

}
$db=new db;



if ( isset( $_POST["email"] ) ) {

	// check and die if either are invalid
	if ( !valid_email( $_POST["email"] ) ) die( "invalid email" );


	$db->insert( "INSERT INTO `entries` ( `data` ) VALUES ( \"" . mysql_real_escape_string( serialize( $_POST ) ) . "\" );" );


	/*
	// message content
	$message_content = "<h2>eGuide Request</h2><hr />" .
		"<p><strong>First Name:</strong><br />" . $_REQUEST["fname"] . "</p>" .
		"<p><strong>Last Name:</strong><br />".$_REQUEST["lname"] . "</p>" .
		"<p><strong>Email:</strong><br />".$_REQUEST["email"] . "</p>" .
		"<hr />" . 
		"<p><small>This message was generated by dukeguide.com.</small></p>";


	// instantiate the mailer script
	$mail = new PHPMailer();
	$mail->IsSMTP();
	$mail->CharSet = 'UTF-8';


	$mail->Host       = SMTPHost;
	$mail->SMTPDebug  = 0;
	$mail->SMTPAuth   = SMTPAuth;
	$mail->SMTPSecure = SMTPSecure;
	$mail->Port       = SMTPPort;
	$mail->Username   = SMTPUsername;
	$mail->Password   = SMTPPassword;

	$mail->From = 'james@jpederson.com';
	$mail->FromName = 'Duke FCU';
	$mail->addAddress( 'james@jpederson.com' );

	$mail->SMTPDebug  = 0;                       // enables SMTP debug information (for testing)
	$mail->WordWrap = 50;                        // Set word wrap to 50 characters
	$mail->isHTML(true);                         // Set email format to HTML

	$mail->Subject = '[dukeguide.com] eGuide Inquiry';
	$mail->Body    = $message_content;
	$mail->AltBody = str_replace("<br />","
	", $message_content );

	if( !$mail->send() ) {
		die( $mail->ErrorInfo );
	} else {
		
	}
	*/

	header( "Location: guide.pdf" );

}


?>